name: insar_qa_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - gdal=3.6.*
  - rasterio
  - geopandas
  - shapely
  - numpy
  - scipy
  - matplotlib
  - jupyterlab
  - python-dotenv  # Added this dependency based on the code
  - pip
  - pip:
    - hyp3_sdk     # ASF's cloud processing submission API
    - asf_search   # ASF's catalog querying API
